version: "3.8"
services:
    api:
        build: ./backend
        command: npm run dev
        volumes:
            - ./backend:/app
        ports: [ "3000:3000" ]
        depends_on: [ mongo ]
    client:
        build: ./frontend
        command: npm run dev
        volumes:
            - ./frontend:/app
        ports: [ "5173:5173" ]
    mongo:
        image: mongo:6
        ports: [ "27017:27017" ]
        volumes:
            - mongo-data:/data/db
    volumes:
        mongo-data:
            